name: CI/CD

on:
    push:
        branches: [main, v2]
    pull_request:
        branches: [main, v2]
    workflow_dispatch:

jobs:
    prepare:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Fetch Dockerfile
              run: |
                  curl -O https://raw.githubusercontent.com/Abhinav-ark/placement_tracker_cicd/main/dockerfiles/placement_tracker_web/Dockerfile

            - name: Cache Dockerfile
              uses: actions/cache@v3
              with:
                  path: ./Dockerfile
                  key: ${{ runner.os }}-dockerfile-${{ github.sha }}

    main-workflow:
        needs: prepare
        uses: Abhinav-ark/placement_tracker_cicd/.github/workflows/placement_tracker_web_deploy.yml@main
        with:
            branch: ${{ github.ref }}
        secrets:
            BACKEND_URL: ${{ secrets.BACKEND_URL }}
            WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
            WIF_SERVICE_ACCOUNT: ${{ secrets.WIF_SERVICE_ACCOUNT }}
